const SCREEN = {
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  HOME_SCREEN: 'HOME_SCREEN',
  USER_SCREEN: 'USER_SCREEN',
  CATEGORY_SCREEN: 'CATEGORY_SCREEN',
  SUGGEST_SCREEN: 'SUGGEST_SCREEN',
  SEARCH_SCREEN: 'SEARCH_SCREEN',
  BOTTOM_TAB: 'BOTTOM_TAB',
  DETAIL_CATEGORY:'DETAIL_CATEGORY',
  DETAIL_PRODUCT:'DETAIL_PRODUCT',

};

export default SCREEN;
