const SCREEN = {
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  HOME_SCREEN: 'HOME_SCREEN',
  USER_SCREEN: 'USER_SCREEN',
  CATEGORY_SCREEN: 'CATEGORY_SCREEN',
  SUGGEST_SCREEN: 'SUGGEST_SCREEN',
  SEARCH_SCREEN: 'SEARCH_SCREEN',
  BOTTOM_TAB: 'BOTTOM_TAB',
  DETAIL_CATEGORY_SCREEN:'DETAIL_CATEGORY',
  DETAIL_PRODUCT_SCREEN:'DETAIL_PRODUCT',
  STORAGE_USER_SCREEN: 'STORAGE_USER_SCREEN',
};

export default SCREEN;
