@baseUrl  = http://mon-973767c9f0f6.herokuapp.com/api

# Categories

# @name getAllCategories
GET {{baseUrl}}/categories

###

# @name getCategoriesPagination
GET {{baseUrl}}/categories?_limit=10&_page=1

###

# @name addNewCategory
POST {{baseUrl}}/categories
Content-Type: application/json

{
    "name":"Laptop new"
}

###

# @name updateCategory
PATCH  {{baseUrl}}/categories/340acabc-e4eb-4451-8530-f00789f7ef7b
Content-Type: application/json

{
    "name":"Electronics new 2"
}

###

# @name deleteCategoryById
DELETE  {{baseUrl}}/categories/340acabc-e4eb-4451-8530-f00789f7ef7b


