@baseUrl = http://mon-973767c9f0f6.herokuapp.com/api
@resourceName = products

# Products

# @name getAll
GET {{baseUrl}}/{{resourceName}}

###

# @name filterProducts
GET {{baseUrl}}/{{resourceName}}?color=red

###

# @name filterProductsLike
GET {{baseUrl}}/{{resourceName}}?name_like=cotton

###

# @name filterProducts
GET {{baseUrl}}/{{resourceName}}?price_gte=900

###

# @name filterProducts
GET {{baseUrl}}/{{resourceName}}?color=red&price_gte=10

###

# @name pagination
GET {{baseUrl}}/{{resourceName}}?page=1&_limit=2

###

# @name sort
GET {{baseUrl}}/{{resourceName}}?_sort=price&_order=asc

###

# @name sortDescending
GET {{baseUrl}}/{{resourceName}}?_sort=price&_order=desc

###

# @name addNew
POST {{baseUrl}}/{{resourceName}}
Content-Type: application/json

{
    "categoryId": "51af4f4f-695b-4f6f-8c8f-ca067cd5f7b0",
    "name": "Small Concrete Pizza",
    "color": "gold",
    "price": 555,
    "description": "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
    "thumbnailUrl": "http://placeimg.com/600/400"
  }

###

# @name update
PATCH  {{baseUrl}}/{{resourceName}}/y93hIFQ
Content-Type: application/json

{
    "name": "Small Concrete Pizza Update",
    "color": "red",
    "price": 666
  }

###

# @name remove
DELETE  {{baseUrl}}/{{resourceName}}/2